---
title: "March 2023 Server Survey Parsed Data"
author: "Arecibo"
date: "2023-03-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse") 
library("readr")
library("ggplot2")
```

# Data Import and Minor Manipulations

Code for importing the data set and making minor modifications to it for ease of use later
in the program.
```{r, echo=FALSE}
# Read in the survey data from the TSV file. Column names not included because they
# take the form of questions and thus are more wordy to rename and can cause issues
# with the pdf knitting with the proper view.
surveyData <- readr::read_tsv("Mar2023ServerSurvey.tsv", col_names = FALSE, 
show_col_types = FALSE)

# Modify the column names to something more easily readable.
surveyData <- surveyData %>% rename("Timestamp" = X1, "Level" = X2, "TopSection" = X3,
"SecondSection" = X4, "PentCity" = X5, "MostEnjoyable" = X6, "MostDisliked" = X7, 
"EnvironmentImprovement" = X8, "AddGenInfo" = X9, "AdditionalSection1" = X10,
"ModerationSatisfaction" = X11, "ModSatNo" = X12, "ModeratorComplaints" = X13,
"ModScreenshots" = X14, "SysBotSatisfaction" = X15, "SysBotConcerns" = X16, "NewBot" = X17,
"AddModInfo" = X18, "AdditionalSection2" = X19, "ChannelSatisfaction" = X20, 
"AddChaSatInfo" = X21, "RoleSatisfaction" = X22, "RoleSatInfo" = X23, "NewColors" = X24,
"Gay-LesbianName" = X25, "Bi-Pan-AceName" = X26, "PronounSatisfaction" = X27,
"AdultSectionFeedback" = X28, "SupportRequestsUsed" = X29, "SupportRequestsOpinions" = X30,
"SupportRequestsModifications" = X31, "SupportRequestsModification" = X32,
"AddChaRoleInfo" = X33, "AdditionalSection3" = X34, "EventParticipation" = X35,
"TextorVCEvents" = X36, "MinecraftBedrockJava" = X37, "PokemonTourney" = X38,
"ChessTourney" = X39, "EventSuggestions" = X40, "EventHandling" = X41,
"EventImprovements" = X42, "EventInterest" = X43, "AddEventInfo" = X44,
"AdditionalSection4" = X45, "ArtCatActivity" = X46, "ArtSectionVisitorType" = X47,
"CriticUse" = X48, "CriticRoleSatisfaction" = X49, "ArtMedium" = X50,
"ArtExpression" = X51, "GalleyDiscussionDivision" = X52, "DivisionSuggestions" = X53,
"ArtRules" = X54, "SpoilerGuidelines" = X55, "CritiqueGuidelines" = X56,
"GuidelineConcerns" = X57, "ArtEventParticipation" = X58, "NewArtEvents" = X59,
"ArtClassInterest" = X60, "ArtFight" = X61, "AddArtInfo" = X62, "AdditionalSection5" = X63,
"SurveyFormatPreference" = X64, "SurveyImprovements" = X65, "SubmissionReady" = X66)

# Removing rows with the original column names, test data, and team joke data.
surveyData <- surveyData %>% filter(surveyData$Timestamp != "Timestamp")
surveyData <- surveyData %>% filter(surveyData$Timestamp != "3/12/2023 22:11:15")
surveyData <- surveyData %>% filter(surveyData$Timestamp != "3/23/2023 22:48:51")

# Adding a row with identifier information.
surveyData <- surveyData %>% mutate(Survey = 0)
for (index in 1:length(surveyData$Timestamp)) {
  surveyData$Survey[index] <- index
}

# Uncomment the line below to check data integrity and view the created tibble.
#surveyData
```

# Results

## Demographic Information / Survey Key
```{r, results='asis', echo=FALSE}
cat("\n")
cat("##", "Summary Information", "  \n")
cat("\n\n")

ggplot(surveyData, aes(x=TopSection, fill=TopSection)) + geom_bar() + 
  labs(title = "Which part of the server are you most active in?") + 
  scale_x_discrete(guide = guide_axis(n.dodge=2))
cat("\n\n")

ggplot(surveyData, aes(x=SecondSection, fill=SecondSection)) + geom_bar() + 
  labs(title = "Which part of the server is your runner up for activity?") + 
  scale_x_discrete(guide = guide_axis(n.dodge=2))
cat("\n")

for (index in 1:length(surveyData$Timestamp)) {
  # Prints out the survey number.
  cat("\n")
  cat("###", "Survey ", surveyData$Survey[index], "  \n")
  cat("\n")
  
  # Prints out the general "demographic" information for the participant.
  cat("##", "Subject Information", "  \n")
  cat("\n")
  cat("Approximate Level: ", surveyData$Level[index], "  \nPrimary Section for Activity: ",
      surveyData$TopSection[index], "  \nSecondary Section for Activity: ", 
      surveyData$SecondSection[index], 
      "  \nIf Pentagram City selected, primary pentagram city channel for activity: ", 
      surveyData$PentCity[index], "  \n")
  cat("\n")
}
```

## General / Universal Feeback
```{r, results='asis', echo=FALSE}
for (index in 1:length(surveyData$Timestamp)) {
  # Prints out the survey number.
  cat("\n")
  cat("###", "Survey ", surveyData$Survey[index], "  \n")
  cat("\n")
  
  # Prints out the responses for the general/universal portion of the survey.
  cat("\n")
  cat("####", "General Survey Response", "  \n")
  cat("\n")
  cat("What part of this server do you enjoy the most? What makes you enjoy it?  \n",
      surveyData$MostEnjoyable[index], "\n\n",
      "What part of this server do you dislike the most? What makes you dislike it?  \n",
      surveyData$MostDisliked[index], "\n\n",
      "What would you change to improve the server environment?  \n",
      surveyData$EnvironmentImprovement[index], "\n\n",
      "Say anything else on your mind here.  \n",
      surveyData$AddGenInfo[index], "  \n")
  cat("\n")
}
```

## Moderation and Bot Feedback
```{r, results='asis', echo=FALSE}
ModBot <- surveyData %>% filter(!is.na(ModerationSatisfaction))

moderatorComplaintCount <- sum(ModBot$ModerationSatisfaction == "No")
evidenceResponseCount <- sum(!is.na(ModBot$ModScreenshots))

cat("\n")
cat("##", "Summary Information", "  \n")
cat("\n")
cat(length(ModBot$Timestamp), " participants elected to participate in this section out of ",
    length(surveyData$Timestamp), " total participants.")
cat("\n\n")

ggplot(ModBot, aes(x=ModerationSatisfaction, fill=ModerationSatisfaction)) + geom_bar() +
  labs(title = "Are you satisfied with the moderation of this server?")
cat("\n")

cat("There were a total of ", moderatorComplaintCount, " moderator complaints made.\n")
cat(evidenceResponseCount, " of which provided evidence.")
cat("\n\n")

ggplot(ModBot, aes(x=SysBotSatisfaction, fill=SysBotSatisfaction)) + geom_bar() + 
  labs(title = "Are you satisfied with the systems and bots that we use in this server?")
cat("\n")

cat("\n")
cat("##", "Relevant Surveys", "  \n")
cat("\n")
for (index in 1:length(ModBot$Timestamp)) {
  # Prints out the survey number.
  cat("\n")
  cat("###", "Survey ", ModBot$Survey[index], "  \n")
  cat("\n")
  
  cat("Are you satisfied with the moderation of this server?  \n",
      ModBot$ModerationSatisfaction[index], "\n\n",
      "If you selected no, please detail what concerns you have about the moderation system.",
      ModBot$ModSatNo[index], "\n\n",
      "Do you have concerns or complaints about any moderator in particular? If you do, detail your complaint here. Be sure to be constructive and include message links to back up complaints. Complaints that do not do either of these things will be discarded.",
      ModBot$ModeratorComplaints[index], "\n\n",
      "Screenshots of the behaviors listed in the question above can be posted here.",
      ModBot$ModScreenshots[index], "\n\n",
      "Are you satisfied with the systems and bots that we use in this server?",
      ModBot$SysBotSatisfaction[index], "\n\n",
      "If you selected no, please detail what concerns you have about the systems and bots we use.",
      ModBot$SysBotConcerns[index], "\n\n",
      "Are there any bots that you would like to see added to the server?",
      ModBot$NewBot[index], "\n\n",
      "Say anything else regarding moderation, systems, and bots we use here.",
      ModBot$AddModInfo[index], "  \n")
  cat("\n")
}
```

## Channel and Role Feedback
```{r, results='asis', echo=FALSE}
ChannelRole <- surveyData %>% filter(!is.na(ChannelSatisfaction))
ChannelRole

ChannelRole$`Gay-LesbianName`[29] <- "Gynesexual/Andro"
ChannelRole$`Bi-Pan-AceName`[6] <- "Bi-Spectrum/Pan-Spectrum"
ChannelRole$`Bi-Pan-AceName`[12] <- "Bi/Pan/Ace/Bi-Spectrum/Pan-Spectrum/Ace-Spectrum"

BiPanCount <- 0
BiSpecPanSpecCount <- 0
AceCount <- 0
ACount <- 0
AceSpecCount <- 0
ASpecCount <- 0

for (index in 1:length(ChannelRole$Timestamp)) {
  if (grepl("Bi/Pan", ChannelRole$`Bi-Pan-AceName`[index]) == TRUE) {
    BiPanCount <- BiPanCount + 1
    if (grepl("Ace", ChannelRole$`Bi-Pan-AceName`[index]) == TRUE) {
      AceCount <- AceCount + 1
    } else {
      ACount <- ACount + 1
    }
  } else if (grepl("Bi-Spectrum/Pan-Spectrum", ChannelRole$`Bi-Pan-AceName`[index]) == TRUE) {
    BiSpecPanSpecCount <- BiSpecPanSpecCount + 1
  }
  
  if (grepl("Ace-Spectrum", ChannelRole$`Bi-Pan-AceName`[index]) == TRUE) {
    AceSpecCount <- AceSpecCount + 1
  } else if (grepl("A-Spectrum", ChannelRole$`Bi-Pan-AceName`[index]) == TRUE) {
    ASpecCount <- ASpecCount + 1
  }
}

BiPanVec <- vector("character", BiPanCount+BiSpecPanSpecCount)

for (i in 1:BiPanCount) {
  BiPanVec[i] <- "Bi/Pan"
}

for (j in (BiPanCount+1):(BiPanCount+BiSpecPanSpecCount)) {
  BiPanVec[j] <- "Bi-Spectrum/Pan-Spectrum"
}

BiPanFrame <- as.tibble(data.frame("Choice" = BiPanVec))

AVec <- vector("character", AceCount+ACount+AceSpecCount+ASpecCount)

for (k in 1:AceCount + 1) {
  AVec[k] <- "Ace"
}

for (l in (AceCount + 1):(AceCount+ACount + 1)) {
  AVec[l] <- "A"
}

for (q in (AceCount + ACount + 1):(AceCount+ACount+AceSpecCount + 1)) {
  AVec[q] <- "Ace-Spectrum"
}

for (w in (AceCount+ACount+AceSpecCount+1):(AceCount+ACount+AceSpecCount+ASpecCount + 1)) {
  AVec[w] <- "A-Spectrum"
}

AVec[1] <- "Ace"

AFrame <- as.tibble(data.frame("Choice" = AVec))

cat("\n")
cat("##", "Summary Information", "  \n")
cat("\n")

cat(length(ChannelRole$Timestamp), " participants elected to participate in this section out of ",
    length(surveyData$Timestamp), " total participants.")
cat("\n\n")

ggplot(ChannelRole, aes(x=ChannelSatisfaction, fill=ChannelSatisfaction)) + geom_bar() + 
  labs(title = "Are you satisfied with the channels and categories in the server?")
cat("\n\n")

ggplot(ChannelRole, aes(x=RoleSatisfaction, fill=RoleSatisfaction)) + geom_bar() + 
  labs(title = "Are you satisfied with all of our self assignable roles?")
cat("\n\n")

cat(sum(!is.na(ChannelRole$NewColors)), " new colors were suggested.")
cat("\n\n")

ggplot(ChannelRole %>% filter(!is.na(ChannelRole$`Gay-LesbianName`)), aes(x=`Gay-LesbianName`, fill=`Gay-LesbianName`)) + geom_bar() + 
  labs(title = "How do you prefer our gay and lesbian attraction roles to be named?")  + 
  scale_x_discrete(guide = guide_axis(n.dodge=2))
cat("\n\n")

ggplot(BiPanFrame, aes(x=Choice, fill=Choice)) + geom_bar() + 
  labs(title="Preferred Bi/Pan Role Name")
cat("\n\n")

ggplot(AFrame, aes(x=Choice, fill=Choice)) + geom_bar() + 
  labs(title="Preferred \'A\' Role Name")
cat("\n\n")

cat("\n")
cat("##", "Relevant Surveys", "  \n")
cat("\n")

for (index in 1:length(ChannelRole$Timestamp)) {
  
  # Prints out the survey number.
  cat("\n")
  cat("###", "Survey ", ChannelRole$Survey[index], "  \n")
  cat("\n")
  
  cat("Are you satisfied with the channels and categories in the server?",
      ChannelRole$ChannelSatisfaction[index], "\n\n",
      "If you’re unsatisfied, what changes would you make to the channels and categories? Are there and channels or categories that you'd like to see added or removed?",
      ChannelRole$AddChaSatInfo[index], "\n\n",
      "Are you satisfied with all of our self assignable roles?",
      ChannelRole$RoleSatisfaction[index], "\n\n",
      "If you aren’t satisfied, what would you like to see changed or added?",
      ChannelRole$RoleSatInfo[index], "\n\n",
      "Are there any colors that you’d like to see added or removed? If so, please leave the color names and hex codes below.",
      ChannelRole$NewColors[index], "\n\n",
      "How do you prefer our gay and lesbian attraction roles to be named? Please only answer this question if you're a group affected by the role name.",
      ChannelRole$`Gay-LesbianName`[index], "\n\n",
      "How do you prefer our bi, pan, and ace attraction roles to be named? Please only answer this question if you're a group affected by the role name.",
      ChannelRole$`Bi-Pan-AceName`[index], "\n\n",
      "Are you satisfied with all the current pronoun roles? If not, what would you add?",
      ChannelRole$PronounSatisfaction[index], "\n\n",
      "IF YOU ARE AN ADULT: Do you think the adult section is adequate, or could it be improved? What changes would you make to this section?",
      ChannelRole$AdultSectionFeedback[index], "\n\n",
      "Do you use #support-requests?",
      ChannelRole$SupportRequestsUsed[index], "\n\n",
      "Do you believe #support-requests needs to be deleted or reformatted?",
      ChannelRole$SupportRequestsOpinions[index], "\n\n",
      "If you have used #support-requests and feel as if it needs to be reformatted, how would you suggest changing the channel? Please explain in depth.",
      ChannelRole$SupportRequestsModifications[index], "\n\n",
      "How would you feel about reformatting #support-requests to a forum or thread channel?",
      ChannelRole$SupportRequestsModification[index], "\n\n",
      "Please say anything else on your mind regarding channels and roles here.",
      ChannelRole$AddChaRoleInfo[index], "  \n")
  cat("\n")
}
```


